/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontSize: {
        xs: ['0.75rem', { lineHeight: '1.45' }],       // 12px - min allowed
        sm: ['0.875rem', { lineHeight: '1.45' }],      // 14px
        base: ['1.0625rem', { lineHeight: '1.45' }],   // 17px - iOS body min
        lg: ['1.1875rem', { lineHeight: '1.45' }],     // 19px - optimal body
        xl: ['1.5rem', { lineHeight: '1.4' }],         // 24px
        '2xl': ['1.875rem', { lineHeight: '1.35' }],   // 30px - body title
        '3xl': ['2.125rem', { lineHeight: '1.3' }],    // 34px - screen title
        '4xl': ['2.75rem', { lineHeight: '1.2' }],     // 44px
      },
      fontFamily: {
        sans: ['-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue', 'Arial', 'sans-serif'],
      },
      borderRadius: {
        'sm': 'calc(var(--radius) - 4px)',
        'md': 'calc(var(--radius) - 2px)',
        'lg': 'var(--radius)',
        'xl': 'calc(var(--radius) + 4px)',
        '2xl': 'calc(var(--radius) + 8px)',
        '3xl': 'calc(var(--radius) + 12px)',
        '4xl': 'calc(var(--radius) + 16px)',
      },
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        card: {
          DEFAULT: 'var(--card)',
          foreground: 'var(--card-foreground)',
        },
        popover: {
          DEFAULT: 'var(--popover)',
          foreground: 'var(--popover-foreground)',
        },
        primary: {
          DEFAULT: 'var(--primary)',
          foreground: 'var(--primary-foreground)',
        },
        secondary: {
          DEFAULT: 'var(--secondary)',
          foreground: 'var(--secondary-foreground)',
        },
        muted: {
          DEFAULT: 'var(--muted)',
          foreground: 'var(--muted-foreground)',
        },
        accent: {
          DEFAULT: 'var(--accent-color)',
          foreground: 'var(--accent-foreground-color)',
        },
        destructive: {
          DEFAULT: 'var(--destructive)',
          foreground: 'var(--destructive-foreground)',
        },
        border: 'var(--border-color)',
        input: 'var(--input)',
        ring: 'var(--ring)',
        chart: {
          '1': 'var(--chart-1)',
          '2': 'var(--chart-2)',
          '3': 'var(--chart-3)',
          '4': 'var(--chart-4)',
          '5': 'var(--chart-5)',
        },
        sidebar: {
          DEFAULT: 'var(--sidebar)',
          foreground: 'var(--sidebar-foreground)',
          primary: 'var(--sidebar-primary)',
          'primary-foreground': 'var(--sidebar-primary-foreground)',
          accent: 'var(--sidebar-accent)',
          'accent-foreground': 'var(--sidebar-accent-foreground)',
          border: 'var(--sidebar-border)',
          ring: 'var(--sidebar-ring)',
        },
        // Direct color palette access
        grayscale: {
          1: 'var(--color-grayscale-1)',
          2: 'var(--color-grayscale-2)',
          3: 'var(--color-grayscale-3)',
          4: 'var(--color-grayscale-4)',
          5: 'var(--color-grayscale-5)',
          6: 'var(--color-grayscale-6)',
          7: 'var(--color-grayscale-7)',
          8: 'var(--color-grayscale-8)',
          9: 'var(--color-grayscale-9)',
          10: 'var(--color-grayscale-10)',
          11: 'var(--color-grayscale-11)',
          12: 'var(--color-grayscale-12)',
          13: 'var(--color-grayscale-13)',
          14: 'var(--color-grayscale-14)',
          15: 'var(--color-grayscale-15)',
          16: 'var(--color-grayscale-16)',
          17: 'var(--color-grayscale-17)',
          18: 'var(--color-grayscale-18)',
          19: 'var(--color-grayscale-19)',
          20: 'var(--color-grayscale-20)',
          21: 'var(--color-grayscale-21)',
          22: 'var(--color-grayscale-22)',
          23: 'var(--color-grayscale-23)',
          24: 'var(--color-grayscale-24)',
          25: 'var(--color-grayscale-25)',
          26: 'var(--color-grayscale-26)',
          27: 'var(--color-grayscale-27)',
          28: 'var(--color-grayscale-28)',
          29: 'var(--color-grayscale-29)',
          30: 'var(--color-grayscale-30)',
          31: 'var(--color-grayscale-31)',
          32: 'var(--color-grayscale-32)',
          33: 'var(--color-grayscale-33)',
          34: 'var(--color-grayscale-34)',
          35: 'var(--color-grayscale-35)',
          36: 'var(--color-grayscale-36)',
          37: 'var(--color-grayscale-37)',
          38: 'var(--color-grayscale-38)',
          39: 'var(--color-grayscale-39)',
          40: 'var(--color-grayscale-40)',
          41: 'var(--color-grayscale-41)',
          42: 'var(--color-grayscale-42)',
          43: 'var(--color-grayscale-43)',
          44: 'var(--color-grayscale-44)',
          45: 'var(--color-grayscale-45)',
          46: 'var(--color-grayscale-46)',
          47: 'var(--color-grayscale-47)',
          48: 'var(--color-grayscale-48)',
          49: 'var(--color-grayscale-49)',
          50: 'var(--color-grayscale-50)',
          51: 'var(--color-grayscale-51)',
          52: 'var(--color-grayscale-52)',
          53: 'var(--color-grayscale-53)',
          54: 'var(--color-grayscale-54)',
          55: 'var(--color-grayscale-55)',
          56: 'var(--color-grayscale-56)',
        },
        green: {
          1: 'var(--color-green-1)',
          2: 'var(--color-green-2)',
          3: 'var(--color-green-3)',
          4: 'var(--color-green-4)',
          5: 'var(--color-green-5)',
          6: 'var(--color-green-6)',
          7: 'var(--color-green-7)',
          8: 'var(--color-green-8)',
          9: 'var(--color-green-9)',
          10: 'var(--color-green-10)',
          11: 'var(--color-green-11)',
          12: 'var(--color-green-12)',
          13: 'var(--color-green-13)',
          14: 'var(--color-green-14)',
          15: 'var(--color-green-15)',
          16: 'var(--color-green-16)',
          17: 'var(--color-green-17)',
          18: 'var(--color-green-18)',
          19: 'var(--color-green-19)',
          20: 'var(--color-green-20)',
          21: 'var(--color-green-21)',
          22: 'var(--color-green-22)',
          23: 'var(--color-green-23)',
          24: 'var(--color-green-24)',
          25: 'var(--color-green-25)',
          26: 'var(--color-green-26)',
          27: 'var(--color-green-27)',
          28: 'var(--color-green-28)',
          29: 'var(--color-green-29)',
          30: 'var(--color-green-30)',
          31: 'var(--color-green-31)',
          32: 'var(--color-green-32)',
          33: 'var(--color-green-33)',
          34: 'var(--color-green-34)',
          35: 'var(--color-green-35)',
          36: 'var(--color-green-36)',
          37: 'var(--color-green-37)',
          38: 'var(--color-green-38)',
        },
        blue: {
          1: 'var(--color-blue-1)',
          2: 'var(--color-blue-2)',
          3: 'var(--color-blue-3)',
          4: 'var(--color-blue-4)',
          5: 'var(--color-blue-5)',
          6: 'var(--color-blue-6)',
          7: 'var(--color-blue-7)',
          8: 'var(--color-blue-8)',
          9: 'var(--color-blue-9)',
          10: 'var(--color-blue-10)',
          11: 'var(--color-blue-11)',
          12: 'var(--color-blue-12)',
          13: 'var(--color-blue-13)',
          14: 'var(--color-blue-14)',
          15: 'var(--color-blue-15)',
          16: 'var(--color-blue-16)',
          17: 'var(--color-blue-17)',
          18: 'var(--color-blue-18)',
          19: 'var(--color-blue-19)',
          20: 'var(--color-blue-20)',
          21: 'var(--color-blue-21)',
          22: 'var(--color-blue-22)',
          23: 'var(--color-blue-23)',
          24: 'var(--color-blue-24)',
          25: 'var(--color-blue-25)',
          26: 'var(--color-blue-26)',
          27: 'var(--color-blue-27)',
          28: 'var(--color-blue-28)',
          29: 'var(--color-blue-29)',
          30: 'var(--color-blue-30)',
          31: 'var(--color-blue-31)',
          32: 'var(--color-blue-32)',
          33: 'var(--color-blue-33)',
          34: 'var(--color-blue-34)',
          35: 'var(--color-blue-35)',
          36: 'var(--color-blue-36)',
          37: 'var(--color-blue-37)',
          38: 'var(--color-blue-38)',
          39: 'var(--color-blue-39)',
          40: 'var(--color-blue-40)',
          41: 'var(--color-blue-41)',
          42: 'var(--color-blue-42)',
          43: 'var(--color-blue-43)',
          44: 'var(--color-blue-44)',
          45: 'var(--color-blue-45)',
          46: 'var(--color-blue-46)',
          47: 'var(--color-blue-47)',
          48: 'var(--color-blue-48)',
          49: 'var(--color-blue-49)',
          50: 'var(--color-blue-50)',
          51: 'var(--color-blue-51)',
          52: 'var(--color-blue-52)',
          53: 'var(--color-blue-53)',
          54: 'var(--color-blue-54)',
          55: 'var(--color-blue-55)',
          56: 'var(--color-blue-56)',
          57: 'var(--color-blue-57)',
          58: 'var(--color-blue-58)',
          59: 'var(--color-blue-59)',
          60: 'var(--color-blue-60)',
          61: 'var(--color-blue-61)',
          62: 'var(--color-blue-62)',
          63: 'var(--color-blue-63)',
          64: 'var(--color-blue-64)',
          65: 'var(--color-blue-65)',
          66: 'var(--color-blue-66)',
          67: 'var(--color-blue-67)',
          68: 'var(--color-blue-68)',
          69: 'var(--color-blue-69)',
          70: 'var(--color-blue-70)',
          71: 'var(--color-blue-71)',
          72: 'var(--color-blue-72)',
          73: 'var(--color-blue-73)',
          74: 'var(--color-blue-74)',
          75: 'var(--color-blue-75)',
          76: 'var(--color-blue-76)',
        },
        red: {
          1: 'var(--color-red-1)',
          2: 'var(--color-red-2)',
          3: 'var(--color-red-3)',
          4: 'var(--color-red-4)',
          5: 'var(--color-red-5)',
          6: 'var(--color-red-6)',
          7: 'var(--color-red-7)',
          8: 'var(--color-red-8)',
          9: 'var(--color-red-9)',
          10: 'var(--color-red-10)',
          11: 'var(--color-red-11)',
          12: 'var(--color-red-12)',
          13: 'var(--color-red-13)',
          14: 'var(--color-red-14)',
          15: 'var(--color-red-15)',
          16: 'var(--color-red-16)',
          17: 'var(--color-red-17)',
          18: 'var(--color-red-18)',
          19: 'var(--color-red-19)',
          20: 'var(--color-red-20)',
          21: 'var(--color-red-21)',
          22: 'var(--color-red-22)',
          23: 'var(--color-red-23)',
        },
        teal: {
          1: 'var(--color-teal-1)',
          2: 'var(--color-teal-2)',
          3: 'var(--color-teal-3)',
          4: 'var(--color-teal-4)',
        },
        purple: {
          1: 'var(--color-purple-1)',
          2: 'var(--color-purple-2)',
          3: 'var(--color-purple-3)',
          4: 'var(--color-purple-4)',
          5: 'var(--color-purple-5)',
          6: 'var(--color-purple-6)',
        },
        pink: {
          1: 'var(--color-pink-1)',
          2: 'var(--color-pink-2)',
          3: 'var(--color-pink-3)',
          4: 'var(--color-pink-4)',
          5: 'var(--color-pink-5)',
        },
        yellow: {
          1: 'var(--color-yellow-1)',
          2: 'var(--color-yellow-2)',
          3: 'var(--color-yellow-3)',
          4: 'var(--color-yellow-4)',
          5: 'var(--color-yellow-5)',
          6: 'var(--color-yellow-6)',
          7: 'var(--color-yellow-7)',
        },
        // Legacy color aliases for backward compatibility
        corca: {
          white: 'var(--corca-white)',
          black: 'var(--corca-black)',
          'dark-grey': 'var(--corca-dark-grey)',
          'light-grey': 'var(--corca-light-grey)',
          'blue-light': 'var(--corca-blue-light)',
          'blue-medium': 'var(--corca-blue-medium)',
          border: 'var(--corca-border)',
        },
        anara: {
          'dark-bg': 'var(--anara-dark-bg)',
          'sidebar-bg': 'var(--anara-sidebar-bg)',
          'nav-bg': 'var(--anara-nav-bg)',
          'dark-text': 'var(--anara-dark-text)',
          'dark-text-muted': 'var(--anara-dark-text-muted)',
          'dark-border': 'var(--anara-dark-border)',
          'light-bg': 'var(--anara-light-bg)',
          'light-text': 'var(--anara-light-text)',
          'light-text-muted': 'var(--anara-light-text-muted)',
          'light-border': 'var(--anara-light-border)',
          'card-bg': 'var(--anara-card-bg)',
          purple: 'var(--anara-purple)',
          'purple-hover': 'var(--anara-purple-hover)',
          blue: 'var(--anara-blue)',
          'blue-light': 'var(--anara-blue-light)',
        },
        // Coursly card background colors - warm, earthy palette
        cardBg: {
          olive: 'var(--card-bg-olive)',
          beige: 'var(--card-bg-beige)',
          blue: 'var(--card-bg-blue)',
          yellow: 'var(--card-bg-yellow)',
          pink: 'var(--card-bg-pink)',
          green: 'var(--card-bg-green)',
          tan: 'var(--card-bg-tan)',
        },
        // Coursly icon accent colors
        iconAccent: {
          brown: 'var(--icon-brown)',
          olive: 'var(--icon-olive)',
          blue: 'var(--icon-blue)',
          yellow: 'var(--icon-yellow)',
          pink: 'var(--icon-pink)',
        },
      },
      keyframes: {
        'accordion-collapse': {
          'from': {
            height: 'var(--accordion-panel-height, auto)',
          },
          'to': {
            height: '0',
          },
        },
        'accordion-expand': {
          'from': {
            height: '0',
          },
          'to': {
            height: 'var(--accordion-panel-height, auto)',
          },
        },
      },
      animation: {
        'accordion-collapse': 'accordion-collapse 200ms ease-out',
        'accordion-expand': 'accordion-expand 200ms ease-out',
      },
    },
  },
  plugins: [],
}


