"""add_tags_system

Revision ID: 30836c5c1a86
Revises: 5842d5a86893
Create Date: 2026-01-08 17:23:12.729876

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "30836c5c1a86"
down_revision: Union[str, Sequence[str], None] = "5842d5a86893"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  # Create tags table
  op.create_table(
    "tags",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("name", sa.String(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_tags_id"), "tags", ["id"], unique=False)
  op.create_index(op.f("ix_tags_name"), "tags", ["name"], unique=True)

  # Create paper_tags association table
  op.create_table(
    "paper_tags",
    sa.Column("paper_id", sa.Integer(), nullable=False),
    sa.Column("tag_id", sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(["paper_id"], ["papers.id"], ondelete="CASCADE"),
    sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("paper_id", "tag_id"),
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_table("paper_tags")
  op.drop_index(op.f("ix_tags_name"), table_name="tags")
  op.drop_index(op.f("ix_tags_id"), table_name="tags")
  op.drop_table("tags")
  # ### end Alembic commands ###
