"""add_timestamps_and_relationships

Revision ID: 3bf56faa48ce
Revises: f0e96b2b58d5
Create Date: 2026-01-07 14:08:22.632517

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = "3bf56faa48ce"
down_revision: Union[str, Sequence[str], None] = "f0e96b2b58d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "paper_groups",
    sa.Column("paper_id", sa.Integer(), nullable=False),
    sa.Column("group_id", sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(
      ["group_id"],
      ["groups.id"],
    ),
    sa.ForeignKeyConstraint(
      ["paper_id"],
      ["papers.id"],
    ),
    sa.PrimaryKeyConstraint("paper_id", "group_id"),
  )
  op.add_column("annotations", sa.Column("created_at", sa.DateTime(), nullable=False))
  op.add_column("annotations", sa.Column("updated_at", sa.DateTime(), nullable=False))
  op.alter_column("annotations", "paper_id", existing_type=sa.INTEGER(), nullable=False)
  op.alter_column(
    "annotations",
    "content",
    existing_type=sa.VARCHAR(),
    type_=sa.Text(),
    nullable=False,
  )
  op.create_index(
    op.f("ix_annotations_paper_id"), "annotations", ["paper_id"], unique=False
  )
  op.drop_constraint(
    op.f("annotations_paper_id_fkey"), "annotations", type_="foreignkey"
  )
  op.create_foreign_key(
    None, "annotations", "papers", ["paper_id"], ["id"], ondelete="CASCADE"
  )
  op.add_column("groups", sa.Column("updated_at", sa.DateTime(), nullable=False))
  op.alter_column("groups", "name", existing_type=sa.VARCHAR(), nullable=False)
  op.alter_column(
    "groups", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
  )
  op.drop_index(op.f("ix_groups_name"), table_name="groups")
  op.create_index(op.f("ix_groups_name"), "groups", ["name"], unique=True)
  op.add_column("papers", sa.Column("url", sa.String(), nullable=True))
  op.add_column("papers", sa.Column("file_path", sa.String(), nullable=True))
  op.add_column("papers", sa.Column("embedding", Vector(384), nullable=True))
  op.add_column("papers", sa.Column("content_text", sa.Text(), nullable=True))
  op.add_column("papers", sa.Column("created_at", sa.DateTime(), nullable=False))
  op.add_column("papers", sa.Column("updated_at", sa.DateTime(), nullable=False))
  op.alter_column("papers", "title", existing_type=sa.VARCHAR(), nullable=False)
  op.create_index(op.f("ix_papers_title"), "papers", ["title"], unique=False)
  op.drop_column("papers", "s3_url")
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column(
    "papers", sa.Column("s3_url", sa.VARCHAR(), autoincrement=False, nullable=True)
  )
  op.drop_index(op.f("ix_papers_title"), table_name="papers")
  op.alter_column("papers", "title", existing_type=sa.VARCHAR(), nullable=True)
  op.drop_column("papers", "updated_at")
  op.drop_column("papers", "created_at")
  op.drop_column("papers", "content_text")
  op.drop_column("papers", "embedding")
  op.drop_column("papers", "file_path")
  op.drop_column("papers", "url")
  op.drop_index(op.f("ix_groups_name"), table_name="groups")
  op.create_index(op.f("ix_groups_name"), "groups", ["name"], unique=False)
  op.alter_column(
    "groups", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
  )
  op.alter_column("groups", "name", existing_type=sa.VARCHAR(), nullable=True)
  op.drop_column("groups", "updated_at")
  op.drop_constraint(None, "annotations", type_="foreignkey")
  op.create_foreign_key(
    op.f("annotations_paper_id_fkey"), "annotations", "papers", ["paper_id"], ["id"]
  )
  op.drop_index(op.f("ix_annotations_paper_id"), table_name="annotations")
  op.alter_column(
    "annotations",
    "content",
    existing_type=sa.Text(),
    type_=sa.VARCHAR(),
    nullable=True,
  )
  op.alter_column("annotations", "paper_id", existing_type=sa.INTEGER(), nullable=True)
  op.drop_column("annotations", "updated_at")
  op.drop_column("annotations", "created_at")
  op.drop_table("paper_groups")
  # ### end Alembic commands ###
