"""add_viewed_count_to_papers

Revision ID: 5842d5a86893
Revises: 6bd396c48b5e
Create Date: 2026-01-08 17:11:11.120060

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5842d5a86893"
down_revision: Union[str, Sequence[str], None] = "6bd396c48b5e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  # Add column as nullable first
  op.add_column("papers", sa.Column("viewed_count", sa.Integer(), nullable=True))
  # Set default value for existing rows
  op.execute("UPDATE papers SET viewed_count = 0 WHERE viewed_count IS NULL")
  # Now make it NOT NULL
  op.alter_column("papers", "viewed_count", nullable=False, server_default="0")
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_column("papers", "viewed_count")
  # ### end Alembic commands ###
