"""add_publication_metadata_fields

Revision ID: 6bd396c48b5e
Revises: 8f161a2cf71e
Create Date: 2026-01-08 17:08:33.660545

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6bd396c48b5e"
down_revision: Union[str, Sequence[str], None] = "8f161a2cf71e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column("papers", sa.Column("volume", sa.String(), nullable=True))
  op.add_column("papers", sa.Column("issue", sa.String(), nullable=True))
  op.add_column("papers", sa.Column("pages", sa.String(), nullable=True))
  op.add_column("papers", sa.Column("isbn", sa.String(), nullable=True))
  op.add_column("papers", sa.Column("issn", sa.String(), nullable=True))
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_column("papers", "issn")
  op.drop_column("papers", "isbn")
  op.drop_column("papers", "pages")
  op.drop_column("papers", "issue")
  op.drop_column("papers", "volume")
  # ### end Alembic commands ###
