"""fix_embedding_dimension_to_768

Revision ID: 81059d98c20c
Revises: 5998eca5338f
Create Date: 2026-01-15 16:26:18.303974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '81059d98c20c'
down_revision: Union[str, Sequence[str], None] = '5998eca5338f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('annotations', 'highlight_type',
    #            existing_type=sa.VARCHAR(),
    #            type_=sa.Enum('method', 'result', 'conclusion', 'key_contribution', name='highlighttype'),
    #            existing_nullable=True)
    
    # First clear existing embeddings as they are incompatible
    op.execute("UPDATE papers SET embedding = NULL")
    
    op.alter_column('papers', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               existing_nullable=True)
    op.alter_column('papers', 'key_findings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('papers', 'reading_guide',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_foreign_key(None, 'papers', 'papers', ['merged_from_paper_id'], ['id'])
    op.create_foreign_key(None, 'papers', 'papers', ['is_duplicate_of'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'papers', type_='foreignkey')
    op.drop_constraint(None, 'papers', type_='foreignkey')
    op.alter_column('papers', 'reading_guide',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('papers', 'key_findings',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('papers', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=True)
    op.alter_column('annotations', 'highlight_type',
               existing_type=sa.Enum('method', 'result', 'conclusion', 'key_contribution', name='highlighttype'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
