"""Add multiple sessions and name field to ChatSession

Revision ID: 8f161a2cf71e
Revises: b2c3d4e5f6a7
Create Date: 2026-01-08 13:50:30.583099

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8f161a2cf71e"
down_revision: Union[str, Sequence[str], None] = "b2c3d4e5f6a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column(
    "chat_sessions",
    sa.Column("name", sa.String(), server_default="New Session", nullable=False),
  )
  op.drop_index(op.f("ix_chat_sessions_paper_id"), table_name="chat_sessions")
  op.create_index(
    op.f("ix_chat_sessions_paper_id"), "chat_sessions", ["paper_id"], unique=False
  )
  op.drop_index(
    op.f("uq_groups_parent_name"),
    table_name="groups",
    postgresql_where="(parent_id IS NOT NULL)",
  )
  op.drop_index(
    op.f("uq_groups_top_level_name"),
    table_name="groups",
    postgresql_where="(parent_id IS NULL)",
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_index(
    op.f("uq_groups_top_level_name"),
    "groups",
    ["name"],
    unique=True,
    postgresql_where="(parent_id IS NULL)",
  )
  op.create_index(
    op.f("uq_groups_parent_name"),
    "groups",
    ["parent_id", "name"],
    unique=True,
    postgresql_where="(parent_id IS NOT NULL)",
  )
  op.drop_index(op.f("ix_chat_sessions_paper_id"), table_name="chat_sessions")
  op.create_index(
    op.f("ix_chat_sessions_paper_id"), "chat_sessions", ["paper_id"], unique=True
  )
  op.drop_column("chat_sessions", "name")
  # ### end Alembic commands ###
