"""Initial_schema

Revision ID: f0e96b2b58d5
Revises:
Create Date: 2026-01-07 13:44:55.712338

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f0e96b2b58d5"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "groups",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("name", sa.String(), nullable=True),
    sa.Column("created_at", sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_groups_id"), "groups", ["id"], unique=False)
  op.create_index(op.f("ix_groups_name"), "groups", ["name"], unique=False)
  op.create_table(
    "papers",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("title", sa.String(), nullable=True),
    sa.Column("doi", sa.String(), nullable=True),
    sa.Column("s3_url", sa.String(), nullable=True),
    sa.Column("vector_id", sa.String(), nullable=True),
    sa.Column("metadata_json", sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_papers_doi"), "papers", ["doi"], unique=True)
  op.create_index(op.f("ix_papers_id"), "papers", ["id"], unique=False)
  op.create_table(
    "annotations",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("paper_id", sa.Integer(), nullable=True),
    sa.Column("content", sa.String(), nullable=True),
    sa.Column("coordinate_data", sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(
      ["paper_id"],
      ["papers.id"],
    ),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_annotations_id"), "annotations", ["id"], unique=False)
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index(op.f("ix_annotations_id"), table_name="annotations")
  op.drop_table("annotations")
  op.drop_index(op.f("ix_papers_id"), table_name="papers")
  op.drop_index(op.f("ix_papers_doi"), table_name="papers")
  op.drop_table("papers")
  op.drop_index(op.f("ix_groups_name"), table_name="groups")
  op.drop_index(op.f("ix_groups_id"), table_name="groups")
  op.drop_table("groups")
  # ### end Alembic commands ###
